"""Detection signals. Each returns a float 0..1 = P(text is AI-generated).

Signal 1 (llm_signal) is semantic — it asks an LLM whether the text reads as
AI. Signal 2 (stylometry_signal, added in M4) is structural.
"""
import os
import re

MODEL = "llama-3.3-70b-versatile"

_SYSTEM = (
    "You are an AI-text detector. Judge whether the user's text was written by a "
    "human or generated by an AI language model. Consider tone, specificity, "
    "hedging, and stylistic coherence. Respond with ONLY a number between 0 and 1: "
    "0 = certainly human, 1 = certainly AI. No words, just the number."
)


def _has_real_key():
    key = os.getenv("GROQ_API_KEY", "")
    return bool(key) and key != "your_key_here"


def _heuristic_fallback(text):
    """Deterministic stand-in used when no Groq key is configured, so the
    system is runnable end-to-end for local testing. Looks for generic
    AI-register phrasing. Documented as a fallback, not the real signal.
    """
    markers = [
        "it is important to note", "furthermore", "in conclusion",
        "stakeholders", "leverage", "delve", "paradigm", "moreover",
        "it is worth noting", "navigate the complexities", "in today's",
        "a testament to", "plays a crucial role", "responsible deployment",
    ]
    low = text.lower()
    hits = sum(1 for m in markers if m in low)
    # 0 hits -> 0.25 (leans human), scales up with marker density
    score = 0.25 + 0.15 * hits
    return max(0.0, min(1.0, score))


def llm_signal(text):
    """Semantic signal via Groq. Falls back to a heuristic without a key."""
    if not _has_real_key():
        return _heuristic_fallback(text)
    try:
        from groq import Groq

        client = Groq(api_key=os.getenv("GROQ_API_KEY"))
        resp = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM},
                {"role": "user", "content": text},
            ],
            temperature=0,
            max_tokens=8,
        )
        raw = resp.choices[0].message.content.strip()
        match = re.search(r"[01](?:\.\d+)?", raw)
        if not match:
            return _heuristic_fallback(text)
        return max(0.0, min(1.0, float(match.group())))
    except Exception:
        # Network/key/parse failure must not crash a submission.
        return _heuristic_fallback(text)


def _sentences(text):
    parts = re.split(r"[.!?]+", text)
    return [p.strip() for p in parts if p.strip()]


def _clamp(x):
    return max(0.0, min(1.0, x))


def stylometry_signal(text):
    """Structural signal. Combines three metrics that differ between human and
    AI prose. AI text is more uniform; human writing is more 'bursty'.
    Returns a float 0..1 = P(AI). Short texts are pulled toward 0.5 because
    their statistics are unreliable.
    """
    words = re.findall(r"[a-zA-Z']+", text.lower())
    n = len(words)
    if n == 0:
        return 0.5
    sents = _sentences(text)

    # 1. Sentence-length burstiness: humans vary a lot, AI is uniform.
    lengths = [len(re.findall(r"[a-zA-Z']+", s)) for s in sents] or [n]
    mean_len = sum(lengths) / len(lengths)
    var = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std = var ** 0.5
    ai_burst = _clamp(1 - std / 10.0)        # low variance -> AI-like

    # 2. Type-token ratio: high diversity reads human; flat mid-range reads AI.
    ttr = len(set(words)) / n
    ai_ttr = _clamp((0.72 - ttr) / 0.40)     # low/mid TTR -> AI-like

    # 3. Punctuation variety: humans use irregular marks (— ; : ( ) … ! ?).
    variety = len(set(re.findall(r"[—;:()\-!?…]", text)))
    ai_punct = _clamp(1 - variety / 5.0)     # few distinct marks -> AI-like

    score = (ai_burst + ai_ttr + ai_punct) / 3.0

    # Reliability: blend toward 0.5 (uncertain) for short inputs.
    if n < 40:
        weight = n / 40.0
        score = 0.5 + (score - 0.5) * weight
    return _clamp(score)


if __name__ == "__main__":
    samples = [
        "It is important to note that stakeholders must leverage synergies.",
        "ok so i finally tried that ramen place and honestly? underwhelming.",
    ]
    for s in samples:
        print(round(llm_signal(s), 3), round(stylometry_signal(s), 3), "::", s[:50])
